# Generated by Django 1.9.4 on 2016-04-29 16:23
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20160429_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='lageruser',
            name='theme',
            field=models.CharField(choices=[('default', 'default'), ('darkly', 'darkly'), ('simplex', 'simplex'), ('superhero', 'superhero'), ('unity', 'unity')], default='default', max_length=50),
        ),
    ]
