# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-27 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20171107_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lageruser',
            name='theme',
            field=models.CharField(choices=[('default', 'default'), ('darkly', 'darkly'), ('simplex', 'simplex'), ('superhero', 'superhero'), ('united', 'united'), ('paper', 'paper')], default='default', max_length=50),
        ),
    ]
