# Generated by Django 2.2.1 on 2019-05-14 14:14

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_view_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'permissions': (('add_department_user', 'Can add a User to a Department'), ('delete_department_user', 'Can remove a User from a Department')), 'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='lageruser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
