# Generated by Django 2.2.10 on 2020-03-12 12:15

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_rm_read_perm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name'], 'permissions': (('add_department_user', 'Can add a User to a Department'), ('delete_department_user', 'Can remove a User from a Department')), 'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='lageruser',
            options={'ordering': ['username'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='lageruser',
            name='theme',
            field=models.CharField(blank=True, choices=[('flatly', 'flatly'), ('darkly', 'darkly'), ('simplex', 'simplex'), ('superhero', 'superhero'), ('united', 'united')], max_length=50),
        ),
    ]
