# Generated by Django 3.2.3 on 2021-05-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20200525_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lageruser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
