language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  # create the database
  - "./manage.py syncdb --noinput"
# command to run tests
script: "./manage.py test devices network"