# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-10 08:35
from __future__ import unicode_literals

import Lagerregal.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Name')),
                ('street', models.CharField(blank=True, max_length=100, verbose_name='Street')),
                ('number', models.CharField(blank=True, max_length=30, verbose_name='Number')),
                ('zipcode', models.CharField(blank=True, max_length=5, verbose_name='ZIP code')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='State')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Building',
                'verbose_name_plural': 'Buildings',
                'permissions': (('read_building', 'Can read Building'),),
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('inventorynumber', models.CharField(blank=True, max_length=50, verbose_name='Inventorynumber')),
                ('serialnumber', models.CharField(blank=True, max_length=50, verbose_name='Serialnumber')),
                ('hostname', models.CharField(blank=True, max_length=40, verbose_name='Hostname')),
                ('description', models.CharField(blank=True, max_length=10000, verbose_name='Description')),
                ('webinterface', models.CharField(blank=True, max_length=60, verbose_name='Webinterface')),
                ('templending', models.BooleanField(default=False, verbose_name='For short term lending')),
                ('manual', models.FileField(blank=True, null=True, upload_to=Lagerregal.utils.get_file_location)),
                ('archived', models.DateTimeField(blank=True, null=True)),
                ('trashed', models.DateTimeField(blank=True, null=True)),
                ('inventoried', models.DateTimeField(blank=True, null=True)),
                ('is_private', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'permissions': (('boss_mails', 'Emails for bosses'), ('managment_mails', 'Emails for managment'), ('support_mails', 'Emails for support'), ('read_device', 'Can read Device'), ('lend_device', 'Can lend Device'), ('read_puppetdetails', 'Read Puppet Details')),
            },
        ),
        migrations.CreateModel(
            name='DeviceInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.CharField(max_length=200, verbose_name='Information')),
            ],
            options={
                'verbose_name': 'Information',
                'verbose_name_plural': 'Information',
            },
        ),
        migrations.CreateModel(
            name='DeviceInformationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyname', models.CharField(max_length=200, verbose_name='Name')),
                ('humanname', models.CharField(max_length=200, verbose_name='Human readable name')),
            ],
            options={
                'verbose_name': 'Information Type',
                'verbose_name_plural': 'Information Type',
            },
        ),
        migrations.CreateModel(
            name='Lending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lenddate', models.DateField(auto_now_add=True)),
                ('duedate', models.DateField(blank=True, null=True)),
                ('duedate_email', models.DateField(blank=True, null=True)),
                ('returndate', models.DateField(blank=True, null=True)),
                ('smalldevice', models.CharField(blank=True, max_length=200, null=True, verbose_name='Small Device')),
            ],
            options={
                'verbose_name': 'Lending',
                'verbose_name_plural': 'Lendings',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Manufacturer')),
            ],
            options={
                'verbose_name': 'Manufacturer',
                'verbose_name_plural': 'Manufacturers',
                'permissions': (('read_manufacturer', 'Can read Manufacturer'),),
            },
        ),
        migrations.CreateModel(
            name='ManufacturerUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('url', models.CharField(max_length=200, verbose_name='Url')),
            ],
            options={
                'permissions': (('read_url', 'Can read Url'),),
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=Lagerregal.utils.get_file_location)),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Picture',
                'verbose_name_plural': 'Pictures',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'permissions': (('read_room', 'Can read Room'),),
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('templatename', models.CharField(max_length=200, verbose_name='Templatename')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=1000, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
                'ordering': ['name'],
                'permissions': (('read_template', 'Can read Template'),),
            },
        ),
    ]
