# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-10 08:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devicetypes', '0001_initial'),
        ('devicegroups', '0002_devicegroup_department'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('devices', '0002_auto_20181010_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='note',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='devices.Device'),
        ),
        migrations.AddField(
            model_name='manufacturerurl',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='urls', to='devices.Manufacturer'),
        ),
        migrations.AddField(
            model_name='lending',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.Device'),
        ),
        migrations.AddField(
            model_name='lending',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Lent to'),
        ),
        migrations.AddField(
            model_name='deviceinformation',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='information', to='devices.Device'),
        ),
        migrations.AddField(
            model_name='deviceinformation',
            name='infotype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.DeviceInformationType'),
        ),
        migrations.AddField(
            model_name='device',
            name='bookmarkers',
            field=models.ManyToManyField(blank=True, related_name='bookmarks', through='devices.Bookmark', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='device',
            name='contact',
            field=models.ForeignKey(blank=True, help_text='Person to contact about using this device', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_contact', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='device',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='device',
            name='currentlending',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currentdevice', to='devices.Lending'),
        ),
        migrations.AddField(
            model_name='device',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='users.Department'),
        ),
        migrations.AddField(
            model_name='device',
            name='devicetype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devicetypes.Type'),
        ),
        migrations.AddField(
            model_name='device',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='devicegroups.Devicegroup'),
        ),
        migrations.AddField(
            model_name='device',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.Manufacturer'),
        ),
        migrations.AddField(
            model_name='device',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.Room'),
        ),
        migrations.AddField(
            model_name='device',
            name='used_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.Device'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.Device'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
