# Generated by Django 1.9.4 on 2016-04-29 15:44
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_auto_20151105_0851'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'permissions': (('boss_mails', 'Emails for bosses'), ('managment_mails', 'Emails for managment'), ('support_mails', 'Emails for support'), ('read_device', 'Can read Device'), ('lend_device', 'Can lend Device'), ('read_puppetdetails', 'Read Puppet Details')), 'verbose_name': 'Device', 'verbose_name_plural': 'Devices'},
        ),
        migrations.AlterField(
            model_name='device',
            name='bookmarkers',
            field=models.ManyToManyField(blank=True, related_name='bookmarks', through='devices.Bookmark', to=settings.AUTH_USER_MODEL),
        ),
    ]
