# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 23:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_auto_20160429_1044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='template',
            options={'ordering': ['name'], 'permissions': (('read_template', 'Can read Template'),), 'verbose_name': 'Template', 'verbose_name_plural': 'Templates'},
        ),
    ]
