# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 13:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_auto_20171026_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='used_in',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.Device'),
        ),
    ]
