# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_device_used_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='uses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_uses', to='devices.Device'),
        ),
        migrations.AlterField(
            model_name='device',
            name='used_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_used_in', to='devices.Device'),
        ),
    ]
