# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_auto_20171107_0824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='used_in',
        ),
        migrations.AlterField(
            model_name='device',
            name='uses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.Device'),
        ),
    ]
