# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-24 13:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_device_used_in_rm_default'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lending',
            options={'verbose_name': 'Lending', 'verbose_name_plural': 'Lendings'},
        ),
    ]
