# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-27 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_device_used_in_rm_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('driver_url', models.CharField(max_length=1000, verbose_name='Drivers')),
                ('support_url', models.CharField(max_length=1000, verbose_name='Support')),
            ],
        ),
    ]
