# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-27 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='driver_url',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Drivers'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='support_url',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Support'),
        ),
    ]
