# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-16 08:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_auto_20171114_0536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='uses',
        ),
        migrations.AddField(
            model_name='device',
            name='used_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_used_in', to='devices.Device'),
        ),
    ]
