# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-30 08:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_auto_20180727_1412'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendor',
            options={'permissions': (('access_vendor', 'Can access Vendor'),)},
        ),
        migrations.AddField(
            model_name='device',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors', to='devices.Vendor'),
        ),
    ]
