# Generated by Django 2.2.3 on 2019-07-24 15:00

from django.db import migrations
from django.db import models

import devices.models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_rm_read_perm'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='url_pattern',
            field=models.CharField(blank=True, max_length=200, validators=[devices.models.validate_manufacturer_url_pattern], verbose_name='URL Pattern'),
        ),
    ]
