# Generated by Django 2.2.10 on 2020-03-12 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0010_auto_20200301_1513'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'permissions': (('boss_mails', 'Emails for bosses'), ('managment_mails', 'Emails for managment'), ('support_mails', 'Emails for support'), ('lend_device', 'Can lend Device'), ('view_devicedetails', 'View Device Details')), 'verbose_name': 'Device', 'verbose_name_plural': 'Devices'},
        ),
    ]
