# Generated by Django 2.2.10 on 2020-05-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0011_auto_20200312_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='operating_system',
            field=models.IntegerField(choices=[('win', 'Windows'), ('mac', 'macOS'), ('linux', 'Linux')], null=True),
        ),
    ]
