# Generated by Django 2.2.10 on 2020-05-09 09:48

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0012_device_operating_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='operating_system',
            field=models.CharField(choices=[('win', 'Windows'), ('mac', 'macOS'), ('linux', 'Linux')], max_length=10, null=True),
        ),
    ]
