# Generated by Django 3.2.3 on 2021-10-20 17:32

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_building_room'),
        ('devices', '0014_auto_20210628_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.room'),
        ),
    ]
