# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-10 08:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Type',
                'verbose_name_plural': 'Types',
                'permissions': (('read_type', 'Can read Type'),),
            },
        ),
        migrations.CreateModel(
            name='TypeAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('regex', models.CharField(blank=True, max_length=500, null=True)),
                ('devicetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devicetypes.Type')),
            ],
            options={
                'verbose_name': 'Type-attribute',
                'verbose_name_plural': 'Type-attributes',
            },
        ),
        migrations.CreateModel(
            name='TypeAttributeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=400)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.Device')),
                ('typeattribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devicetypes.TypeAttribute')),
            ],
            options={
                'verbose_name': 'Type-attribute value',
                'verbose_name_plural': 'Type-attribute values',
            },
        ),
    ]
