# Generated by Django 2.2.1 on 2019-05-14 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devicetypes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'Type', 'verbose_name_plural': 'Types'},
        ),
    ]
