# Generated by Django 2.2.10 on 2020-05-04 11:20

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('devicetypes', '0003_auto_20200312_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='automatic_data',
            field=models.BooleanField(default=False, verbose_name='Automatic Data'),
        ),
    ]
