# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-10 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devicegroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Devicegroup',
                'verbose_name_plural': 'Devicegroups',
                'permissions': (('read_devicegroup', 'Can read Devicegroup'),),
            },
        ),
    ]
