# Generated by Django 2.2.1 on 2019-05-14 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devicegroups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicegroup',
            options={'verbose_name': 'Devicegroup', 'verbose_name_plural': 'Devicegroups'},
        ),
    ]
