# Generated by Django 2.2.1 on 2019-05-14 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ipaddress',
            options={'verbose_name': 'IP-Address', 'verbose_name_plural': 'IP-Addresses'},
        ),
    ]
