# Generated by Django 2.2.10 on 2020-03-12 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_rm_read_perm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ipaddress',
            options={'ordering': ['address'], 'verbose_name': 'IP-Address', 'verbose_name_plural': 'IP-Addresses'},
        ),
    ]
