# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-10 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devicetag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('devices', models.ManyToManyField(related_name='tags', to='devices.Device')),
            ],
            options={
                'verbose_name': 'Devicetag',
                'verbose_name_plural': 'Devicegtag',
                'permissions': (('read_devicetag', 'Can read Devicetag'),),
            },
        ),
    ]
