# Generated by Django 3.2.3 on 2021-06-28 12:03

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_auto_20200312_1315'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Building',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=200, unique=True, verbose_name='Name')),
                        ('street', models.CharField(blank=True, max_length=100, verbose_name='Street')),
                        ('number', models.CharField(blank=True, max_length=30, verbose_name='Number')),
                        ('zipcode', models.CharField(blank=True, max_length=5, verbose_name='ZIP code')),
                        ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                        ('state', models.CharField(blank=True, max_length=100, verbose_name='State')),
                        ('country', models.CharField(blank=True, max_length=100, verbose_name='Country')),
                    ],
                    options={
                        'verbose_name': 'Building',
                        'verbose_name_plural': 'Buildings',
                        'db_table': 'devices_building',
                        'ordering': ['name'],
                    },
                ),
                migrations.CreateModel(
                    name='Room',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=200, verbose_name='Name')),
                        ('building', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.building')),
                        ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='locations.section')),
                    ],
                    options={
                        'verbose_name': 'Room',
                        'verbose_name_plural': 'Rooms',
                        'db_table': 'devices_room',
                        'ordering': ['name'],
                    },
                ),
            ],
            database_operations=[],
        )
    ]
