# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-10 08:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('devices', '0002_auto_20181010_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=500, verbose_name='Subject')),
                ('body', models.CharField(max_length=10000, verbose_name='Body')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.Device')),
            ],
        ),
        migrations.CreateModel(
            name='MailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Name')),
                ('subject', models.CharField(max_length=500, verbose_name='Subject')),
                ('body', models.CharField(max_length=10000, verbose_name='Body')),
                ('usage', models.CharField(blank=True, choices=[('lent', 'Device has been lent'), ('new', 'New Device is created'), ('reminder', 'Reminder that device is still owned'), ('returned', 'Device has been returned by user'), ('room', 'Room has been changed'), ('overdue', 'Reminder that device is overdue'), ('owner', 'Lending owner has been changed'), ('trashed', 'Device has been trashed')], max_length=200, null=True, verbose_name='Usage')),
            ],
            options={
                'verbose_name': 'Mailtemplate',
                'verbose_name_plural': 'Mailtemplates',
                'ordering': ['name'],
                'permissions': (('read_mailtemplate', 'Can read Mailtemplate'),),
            },
        ),
        migrations.CreateModel(
            name='MailTemplateRecipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('mailtemplate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_recipients', to='mail.MailTemplate')),
            ],
        ),
        migrations.AddField(
            model_name='mailhistory',
            name='mailtemplate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mail.MailTemplate'),
        ),
    ]
