# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 23:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailtemplate',
            options={'ordering': ['name'], 'permissions': (('read_mailtemplate', 'Can read Mailtemplate'),), 'verbose_name': 'Mailtemplate', 'verbose_name_plural': 'Mailtemplates'},
        ),
    ]
