# Generated by Django 1.11.13 on 2018-10-05 13:37
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_auto_20180806_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailtemplate',
            name='usage',
            field=models.CharField(blank=True, choices=[('new', 'New Device is created'), ('room', 'Room has been changed'), ('owner', 'Lending owner has been changed'), ('reminder', 'Reminder that device is still owned'), ('overdue', 'Reminder that device is overdue'), ('returned', 'Device has been returned by user'), ('trashed', 'Device has been trashed')], max_length=200, null=True, verbose_name='Usage'),
        ),
    ]
