# Generated by Django 2.2.1 on 2019-05-14 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0005_auto_20181006_1619'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailtemplate',
            options={'ordering': ['name'], 'verbose_name': 'Mailtemplate', 'verbose_name_plural': 'Mailtemplates'},
        ),
    ]
